client_config_backend: settings
client_config:
  client_id: ${GOOGLE_CLIENT_ID}
  client_secret: ${GOOGLE_CLIENT_SECRET}

save_credentials: True
get_refresh_token: True
save_credentials_backend: file
save_credentials_file: "credentials.json"

oauth_scope:
  - "https://www.googleapis.com/auth/drive"
