name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  backend-build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout backend code
      uses: actions/checkout@v3
      with:
        context: './backend'
        file: './backend/Dockerfile'
    - name: Build the Docker image for backend
      run: docker build --file ./backend/Dockerfile --tag backend-image-name:$(date +%s) .

  frontend-build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout frontend code
      uses: actions/checkout@v3
      with:
        context: './frontend'
        file: './frontend/Dockerfile'
    - name: Build the Docker image for frontend
      run: docker build --file ./backend/Dockerfile --tag frontend-image-name:$(date +%s) .
