name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

env:
  PROD_BACKEND_PORT: 5001
  DEV_BACKEND_PORT: 5003
  PROD_FRONTEND_PORT: 5002
  DEV_FRONTEND_PORT: 5004

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout backend code
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push the Docker image for backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        platforms: linux/arm64
        push: true
        tags: |
          themanwholikestocode/archive-me-prod:backend-${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' && 'development' || 'production' }}
        build-args: |
          CLIENT_CREDENTIALS_JSON=${{ secrets.CLIENT_CREDENTIALS_JSON }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          PORT=${{ (github.event_name == 'pull_request' || github.ref == 'refs/heads/main') && env.DEV_BACKEND_PORT || env.PROD_BACKEND_PORT }}
          
  frontend-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout frontend code
      uses: actions/checkout@v3
  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
    - name: Build and push the Docker image for frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        platforms: linux/arm64
        push: true
        tags: |
          themanwholikestocode/archive-me-prod:frontend-${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' && 'development' || 'production' }}
        build-args: |
          PORT=${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' && env.DEV_FRONTEND_PORT || env.PROD_FRONTEND_PORT }}
