name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout backend code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push the Docker image for backend
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: themanwholikestocode/archive-me-prod:backend-${{ github.event_name == 'pull_request' && 'development' || 'production' }}
        build-args: |
          BUILDPLATFORM=linux/amd64

  frontend-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout frontend code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push the Docker image for frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: themanwholikestocode/archive-me-prod:frontend-${{ github.event_name == 'pull_request' && 'development' || 'production' }}
        build-args: |
          BUILDPLATFORM=linux/amd64
